baseURL = "https://okal.me"
languageCode = "en-gb"
title = "Okal Otieno"
theme = "manis"

[params]
linkedin = "https://www.linkedin.com/in/okalotieno/"
github = "https://www.linkedin.com/in/okalotieno/"

[[menu.main]]
identifer = "about"
name = "About"
url = "/about/"
weight = 1
